// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package gen_queries

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Appointment struct {
	ID        uuid.UUID
	PatientID uuid.NullUUID
	DoctorID  uuid.NullUUID
	StartTime time.Time
	EndTime   time.Time
	Status    string
}

type AppointmentCancellation struct {
	ID            uuid.UUID
	AppointmentID uuid.UUID
	PatientID     uuid.UUID
	Reason        string
	CancelledAt   sql.NullTime
}

type Doctor struct {
	ID   uuid.UUID
	Name string
}

type Patient struct {
	ID    uuid.UUID
	Name  string
	Email string
}

type Schedule struct {
	ID        uuid.UUID
	DoctorID  uuid.UUID
	StartTime time.Time
	EndTime   time.Time
	DayOfWeek int16
}
