// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package gen_queries

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addAppointmentCancellation = `-- name: AddAppointmentCancellation :one
INSERT INTO appointment_cancellations
(appointment_id, patient_id, reason)
VALUES ($1, $2, $3)
RETURNING id, appointment_id, patient_id, reason
`

type AddAppointmentCancellationParams struct {
	AppointmentID uuid.UUID
	PatientID     uuid.UUID
	Reason        string
}

type AddAppointmentCancellationRow struct {
	ID            uuid.UUID
	AppointmentID uuid.UUID
	PatientID     uuid.UUID
	Reason        string
}

func (q *Queries) AddAppointmentCancellation(ctx context.Context, arg AddAppointmentCancellationParams) (AddAppointmentCancellationRow, error) {
	row := q.db.QueryRowContext(ctx, addAppointmentCancellation, arg.AppointmentID, arg.PatientID, arg.Reason)
	var i AddAppointmentCancellationRow
	err := row.Scan(
		&i.ID,
		&i.AppointmentID,
		&i.PatientID,
		&i.Reason,
	)
	return i, err
}

const createAppointment = `-- name: CreateAppointment :one
INSERT INTO appointments 
(patient_id, doctor_id, start_time, end_time, status) 
VALUES (
$1, $2, $3, $4, $5
) RETURNING id, patient_id, doctor_id, start_time, end_time, status
`

type CreateAppointmentParams struct {
	PatientID uuid.NullUUID
	DoctorID  uuid.NullUUID
	StartTime time.Time
	EndTime   time.Time
	Status    string
}

func (q *Queries) CreateAppointment(ctx context.Context, arg CreateAppointmentParams) (Appointment, error) {
	row := q.db.QueryRowContext(ctx, createAppointment,
		arg.PatientID,
		arg.DoctorID,
		arg.StartTime,
		arg.EndTime,
		arg.Status,
	)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.DoctorID,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
	)
	return i, err
}

const createDoctor = `-- name: CreateDoctor :one
INSERT INTO doctors (name) VALUES ($1) RETURNING id, name
`

func (q *Queries) CreateDoctor(ctx context.Context, name string) (Doctor, error) {
	row := q.db.QueryRowContext(ctx, createDoctor, name)
	var i Doctor
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const createPatient = `-- name: CreatePatient :one
INSERT INTO patients (name, email) VALUES ($1, $2) RETURNING id, name, email
`

type CreatePatientParams struct {
	Name  string
	Email string
}

func (q *Queries) CreatePatient(ctx context.Context, arg CreatePatientParams) (Patient, error) {
	row := q.db.QueryRowContext(ctx, createPatient, arg.Name, arg.Email)
	var i Patient
	err := row.Scan(&i.ID, &i.Name, &i.Email)
	return i, err
}

const createSchedule = `-- name: CreateSchedule :one
INSERT INTO schedules (doctor_id, day_of_week, start_time, end_time) VALUES ($1, $2, $3, $4) RETURNING id, doctor_id, day_of_week, start_time, end_time
`

type CreateScheduleParams struct {
	DoctorID  uuid.UUID
	DayOfWeek int16
	StartTime time.Time
	EndTime   time.Time
}

type CreateScheduleRow struct {
	ID        uuid.UUID
	DoctorID  uuid.UUID
	DayOfWeek int16
	StartTime time.Time
	EndTime   time.Time
}

func (q *Queries) CreateSchedule(ctx context.Context, arg CreateScheduleParams) (CreateScheduleRow, error) {
	row := q.db.QueryRowContext(ctx, createSchedule,
		arg.DoctorID,
		arg.DayOfWeek,
		arg.StartTime,
		arg.EndTime,
	)
	var i CreateScheduleRow
	err := row.Scan(
		&i.ID,
		&i.DoctorID,
		&i.DayOfWeek,
		&i.StartTime,
		&i.EndTime,
	)
	return i, err
}

const getAppointmentByID = `-- name: GetAppointmentByID :one
SELECT id, patient_id, doctor_id, start_time, end_time, statusFROM appointments 
WHERE id = $1
`

func (q *Queries) GetAppointmentByID(ctx context.Context, id uuid.UUID) (Appointment, error) {
	row := q.db.QueryRowContext(ctx, getAppointmentByID, id)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.DoctorID,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
	)
	return i, err
}

const getAppointmentsByDoctorID = `-- name: GetAppointmentsByDoctorID :many
SELECT id, patient_id, doctor_id, start_time, end_time, status FROM appointments WHERE doctor_id = $1
`

func (q *Queries) GetAppointmentsByDoctorID(ctx context.Context, doctorID uuid.NullUUID) ([]Appointment, error) {
	rows, err := q.db.QueryContext(ctx, getAppointmentsByDoctorID, doctorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Appointment
	for rows.Next() {
		var i Appointment
		if err := rows.Scan(
			&i.ID,
			&i.PatientID,
			&i.DoctorID,
			&i.StartTime,
			&i.EndTime,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAppointmentsByDoctorIDAndStartAndEndTime = `-- name: GetAppointmentsByDoctorIDAndStartAndEndTime :many
SELECT id, patient_id, doctor_id, start_time, end_time, status FROM appointments 
WHERE doctor_id = $1 AND start_time = $2 AND end_time = $3
`

type GetAppointmentsByDoctorIDAndStartAndEndTimeParams struct {
	DoctorID  uuid.NullUUID
	StartTime time.Time
	EndTime   time.Time
}

func (q *Queries) GetAppointmentsByDoctorIDAndStartAndEndTime(ctx context.Context, arg GetAppointmentsByDoctorIDAndStartAndEndTimeParams) ([]Appointment, error) {
	rows, err := q.db.QueryContext(ctx, getAppointmentsByDoctorIDAndStartAndEndTime, arg.DoctorID, arg.StartTime, arg.EndTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Appointment
	for rows.Next() {
		var i Appointment
		if err := rows.Scan(
			&i.ID,
			&i.PatientID,
			&i.DoctorID,
			&i.StartTime,
			&i.EndTime,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDoctorSceduleforDayOfWeek = `-- name: GetDoctorSceduleforDayOfWeek :many
SELECT id, doctor_id, start_time, end_time, day_of_week FROM schedules WHERE doctor_id = $1 AND day_of_week = $2
`

type GetDoctorSceduleforDayOfWeekParams struct {
	DoctorID  uuid.UUID
	DayOfWeek int16
}

func (q *Queries) GetDoctorSceduleforDayOfWeek(ctx context.Context, arg GetDoctorSceduleforDayOfWeekParams) ([]Schedule, error) {
	rows, err := q.db.QueryContext(ctx, getDoctorSceduleforDayOfWeek, arg.DoctorID, arg.DayOfWeek)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Schedule
	for rows.Next() {
		var i Schedule
		if err := rows.Scan(
			&i.ID,
			&i.DoctorID,
			&i.StartTime,
			&i.EndTime,
			&i.DayOfWeek,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDoctors = `-- name: GetDoctors :many
SELECT id, name FROM doctors
`

func (q *Queries) GetDoctors(ctx context.Context) ([]Doctor, error) {
	rows, err := q.db.QueryContext(ctx, getDoctors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Doctor
	for rows.Next() {
		var i Doctor
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUpcomingAppointmentsByPatientID = `-- name: GetUpcomingAppointmentsByPatientID :many
SELECT id, patient_id, doctor_id, start_time, end_time, status FROM appointments WHERE patient_id = $1 AND start_time > CURRENT_TIMESTAMP ORDER BY start_time DESC
`

func (q *Queries) GetUpcomingAppointmentsByPatientID(ctx context.Context, patientID uuid.NullUUID) ([]Appointment, error) {
	rows, err := q.db.QueryContext(ctx, getUpcomingAppointmentsByPatientID, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Appointment
	for rows.Next() {
		var i Appointment
		if err := rows.Scan(
			&i.ID,
			&i.PatientID,
			&i.DoctorID,
			&i.StartTime,
			&i.EndTime,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAppointment = `-- name: UpdateAppointment :one
UPDATE appointments
SET patient_id = coalesce($1, patient_id), doctor_id = coalesce($2, doctor_id), start_time = coalesce($3, start_time), end_time = coalesce($4, end_time), status = coalesce($5, status)
WHERE id = $6
RETURNING id, patient_id, doctor_id, start_time, end_time, status
`

type UpdateAppointmentParams struct {
	PatientID uuid.NullUUID
	DoctorID  uuid.NullUUID
	StartTime time.Time
	EndTime   time.Time
	Status    string
	ID        uuid.UUID
}

func (q *Queries) UpdateAppointment(ctx context.Context, arg UpdateAppointmentParams) (Appointment, error) {
	row := q.db.QueryRowContext(ctx, updateAppointment,
		arg.PatientID,
		arg.DoctorID,
		arg.StartTime,
		arg.EndTime,
		arg.Status,
		arg.ID,
	)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.DoctorID,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
	)
	return i, err
}

const updateAppointmentStatus = `-- name: UpdateAppointmentStatus :exec
UPDATE appointments SET status = $1 WHERE id = $2
`

type UpdateAppointmentStatusParams struct {
	Status string
	ID     uuid.UUID
}

func (q *Queries) UpdateAppointmentStatus(ctx context.Context, arg UpdateAppointmentStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateAppointmentStatus, arg.Status, arg.ID)
	return err
}
